name: Create Service Definition Datadog
on:
  push:
    branches:
      - "dev"
  workflow_dispatch:
jobs:
  datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          repository: bruno561/opentelemetry-demo
          ref: 'dev'
  service-catalog:
    needs: datadog
    strategy:
      matrix:
        service: [hello-world6, hello-world7]
        squad: [squad-name]
        email: [squad@avenue.us]
        slack-support-channel: ['https://team-name-here.slack.com/archives/ABC123']
        repos:
           - { name: ["repo-test", "repo-test2"], url: ["url-test", "url-test2"], provider: ["provider-test", "provider-test2"] }
        tags:
          - name: name1
            value: value1
          - name: name2
            value: value2
      fail-fast: false
    uses: bruno561/reusable-workflows/.github/workflows/datadog-service-definition.yml@main
    secrets: inherit
    with:
      serviceName: ${{ matrix.service }}
      emailName: ${{ matrix.email }}
      slackChannelName: ${{ matrix.slack-support-channel }}
      squadName: ${{ matrix.squad }}
      reposName: ${{ matrix.repos.name }}
      reposURL: ${{ matrix.repos.url }}
      reposProvider: ${{ matrix.repos.provider }}
      tagsName: "${{ matrix.tags.name }}: ${{ matrix.tags.value }}"
