name: Create Service Definition Datadog
on:
  push:
    branches:
      - "dev"
jobs:
  datadog:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     service: [hello-world3, hello-world4]
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          repository: bruno561/opentelemetry-demo
          ref: 'dev'
      - name: List
        run: ls -lha .github/workflows
  service-catalog:
    needs: datadog
      # - name: Service Catalog
    uses: bruno561/reusable-workflows/.github/workflows/datadog-service-definition.yml@main
    with:
      serviceName: hello-world5