name: Deployment
on:
  push:
    branches:
      - "dev"
jobs:
  datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Datadog Service Spec
        uses: bruno561/actions/datadog_service@main
        with:
          spec_file: src/${{ matrix.src }}/datadog.yml
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_application_key: ${{ secrets.DD_APPLICATION_KEY }}
