name: Create Service Definition Datadog
on:
  push:
    branches:
      - "dev"
jobs:
  datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          repository: bruno561/opentelemetry-demo
          ref: 'dev'
      # - name: List
      #   run: ls -lha .github/workflows
  service-catalog:
    needs: datadog
    strategy:
      matrix:
        service: [hello-world6, hello-world7]
        include:
          - email: hello-world6
      # - name: Service Catalog
    uses: bruno561/reusable-workflows/.github/workflows/datadog-service-definition.yml@main
    secrets: inherit
    with:
      serviceName: ${{ matrix.service }}
