name: Create Service Definition Datadog
on:
  push:
    branches:
      - "dev"
  workflow_dispatch:
jobs:
  datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          repository: bruno561/opentelemetry-demo
          ref: 'dev'
      - name: Read file and set output
        id: read_file
        run: |
          echo "::set-output name=file_content::$(cat path/to/file.txt)"
      - name: Use output variable
        run: |
          echo "File contents: ${{ steps.read_file.outputs.file_content }}"
  service-catalog:
    needs: datadog
    strategy:
      matrix:
        service: [hello-world6, hello-world7]
        email: [squad@avenue.us]
        slack-support-channel: ['https://team-name-here.slack.com/archives/ABC123']
        repos: ${{ fromJson('.github/workflows/repos.json').repos }}
        include:
          - service: hello-world8
            email: custom-email
            slack-support-channel: ['https://team-name-here.slack.com/archives/ABC123']
            repos: ${{ fromJson('.github/workflows/repos.json').repos }}
      fail-fast: false
    uses: bruno561/reusable-workflows/.github/workflows/datadog-service-definition.yml@main
    secrets: inherit
    with:
      serviceName: ${{ matrix.service }}
      emailName: ${{ matrix.email }}
      slackChannelName: ${{ matrix.slack-support-channel }}
      reposName: ${{ matrix.repos }}
      