name: Delete Service Definition
on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'The name of the service to delete'
        required: true
jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
  delete-service-definition:
    needs: get-code
    uses: bruno561/reusable-workflows/.github/workflows/delete-service-definition.yml@main
    secrets: inherit
    with:
      service_name: "${{ inputs.service_name }}"