name: Delete Service Definition
on:
  workflow_dispatch:
    inputs:
      serviceName:
        description: 'The name of the service to delete'
        required: true
jobs:
  delete-service-definition:
    permissions:
      contents: read
    uses: bruno561/reusable-workflows/.github/workflows/delete-service-definition.yml@main
    secrets: inherit
    with:
      serviceName: "${{ inputs.serviceName }}"
