name: Delete Service Definition
on:
  push:
    branches:
      - "dev"
  workflow_dispatch:
jobs:
  datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Datadog Service Spec
        uses: bruno561/actions/datadog_service@main
        with:
          dd_api_key: ${{ secrets.DD_API_KEY }}
          dd_application_key: ${{ secrets.DD_APPLICATION_KEY }}
      - name: Delete Service Definition
        run: |
          # Path parameters
          export service_name="featureflagsservice"
          # Curl command
          curl -X DELETE "https://api.datadoghq.com/api/v2/services/definitions/featureflagsservice" \
          -H "Accept: application/json" \
          -H "DD-API-KEY: ${DD_API_KEY}" \
          -H "DD-APPLICATION-KEY: ${DD_APPLICATION_KEY}"