name: Create Service Definition Datadog
on:
  push:
    branches:
      - "dev"
  # workflow_dispatch:
jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
  create-service-definition:
    needs: get-code
    strategy:
      matrix:
        service: [cross-mfaservice]
        squad: [cross]
        email: [squad@company.com]
        slack-support-channel: ['https://team-name-here.slack.com/archives/ABC123']
        docs: [{url: "https://www.atlassian.com/br/software/confluence"}]
        links: [{url: "https://grafana.com"}]
        # tags: [{tag: "key1:value1"}, {tag: "key2:value2"}]
        # include:
        #   - service: service2
        #     squad: squad2
        #     email: squad@company.com
        #     slack-support-channel: 'https://team-name-here.slack.com/archives/ABC123'
        #     # contacts: {name: "contact2", type: "email", value: "test"} 
        #     docs: {url: "https://www.atlassian.com/br/software/confluence"} 
        #     links: {url: "https://grafana.com"}
        #     # repos: {name: "reponame2"}
        #     tags: {tag: "key1:value1"}, {tag: "key2:value2"}
      fail-fast: false
    uses: bruno561/reusable-workflows/.github/workflows/datadog-service-definition.yml@main
    secrets: inherit
    with:
      serviceName: ${{ matrix.service }}
      emailName: ${{ matrix.email }}
      slackChannelName: ${{ matrix.slack-support-channel }}
      squadName: ${{ matrix.squad }}
      docUrl: ${{ matrix.docs.url }}
      grafanaUrl: ${{ matrix.links.url }}
      # tagName1: ${{ matrix.tags.tag1 }}
      # tagName2: ${{ matrix.tags.tag2 }}