name: Create Service Definition Datadog
on:
  push:
    branches:
      - "dev"
  # workflow_dispatch:
jobs:
  create-service-definition:
    permissions:
      contents: read
    strategy:
      matrix:
        service: [bruno]
        squad: [squad]
        email: [squad@company.com]
        slack-channel: ['https://team-name-here.slack.com/archives/ABC123']
        docs: ["https://www.atlassian.com/br/software/confluence"]
        links: [{url: "https://grafana.com"}]
        tags: [{tag1: "app:loadgenerator", tag2: "key2:value2"}]
      fail-fast: false
    uses: bruno561/reusable-workflows/.github/workflows/datadog-service-definition.yml@main
    secrets: inherit
    with:
      serviceName: ${{ matrix.service }}
      emailName: ${{ matrix.email }}
      slackChannelName: ${{ matrix.slack-channel }}
      squadName: ${{ matrix.squad }}
      docUrl: ${{ matrix.docs }}
      grafanaUrl: ${{ matrix.links.url }}
      # tagName1: ${{ matrix.tags.tag1 }}
      # tagName2: ${{ matrix.tags.tag2 }}

