name: Create Service Definition Datadog
on:
  push:
    branches:
      - "dev"
  workflow_dispatch:
jobs:
  datadog:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          repository: bruno561/opentelemetry-demo
          ref: 'dev'
  service-catalog:
    needs: datadog
    strategy:
      matrix:
        service: [service1]
        squad: [squad1]
        email: [squad@company.com]
        slack-support-channel: ['https://team-name-here.slack.com/archives/ABC123']
        contacts: [{name: [contact1, contact2], type: [email1, email2], value: [test1, test2]}]
        docs:
          - name: doc1
            url: https://www.atlassian.com/br/software/confluence
            provider: Confluence
        links:
          - name: grafana
            url: https://grafana.com
            type: dashboard
        repos: 
          - name: reponame
            url: https://github.com
            provider: github
        tags: [{tag1: "key:value", tag2: "key:value2"}]
        include:
          - service: sevice2
            squad: squad2
            email: squad@company.com
            slack-support-channel: 'https://team-name-here.slack.com/archives/ABC123'
            contacts:
              - name: contact2
                type: email
                value: test
            docs:
              - name: doc2
                url: https://www.atlassian.com/br/software/confluence
                provider: Confluence
            links:
              - name: grafana
                url: https://grafana.com
                type: dashboard
            repos: 
              - name: reponame
                url: https://github.com
                provider: github
            tags: {tag1: "key:value", tag2: "key:value2"}
          - service: sevice3
            squad: squad3
            email: squad@company.com
            slack-support-channel: 'https://team-name-here.slack.com/archives/ABC123'
            contacts:
              - name: contact3
                type: email
                value: test
            docs:
              - name: doc3
                url: https://www.atlassian.com/br/software/confluence
                provider: Confluence
            links:
              - name: grafana
                url: https://grafana.com
                type: dashboard
            repos: 
              - name: reponame
                url: https://github.com
                provider: github
            tags: {tag1: "key:value", tag2: "key:value2"}
      fail-fast: false
    uses: bruno561/reusable-workflows/.github/workflows/datadog-service-definition.yml@main
    secrets: inherit
    with:
      serviceName: ${{ matrix.service }}
      emailName: ${{ matrix.email }}
      slackChannelName: ${{ matrix.slack-support-channel }}
      squadName: ${{ matrix.squad }}
      contactName: ${{ matrix.contacts.name }}
      contactType: ${{ matrix.contacts.type }}
      contactValue: ${{ matrix.contacts.value }}
      docName: ${{ matrix.docs.name }}
      docUrl: ${{ matrix.docs.url }}
      docProvider: ${{ matrix.docs.provider }}
      linkName: ${{ matrix.links.name }}
      linkUrl: ${{ matrix.links.url }}
      linkType: ${{ matrix.links.type }}
      # reposMatrix: ${{ matrix.repos.name }} ${{ matrix.repo.url }} ${{ matrix.repo.provider }}
      reposName: ${{ matrix.repos.name }}
      reposURL: ${{ matrix.repos.url }}
      reposProvider: ${{ matrix.repos.provider }}
      tagName1: ${{ matrix.tags.tag1 }}
      tagName2: ${{ matrix.tags.tag2 }}